# Generated by Django 5.1.5 on 2025-02-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/detection')),
                ('precision', models.FloatField(default=0.0)),
            ],
        ),
    ]
