# Generated by Django 5.1.5 on 2025-02-19 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='detection',
            name='location',
        ),
        migrations.AddField(
            model_name='detection',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.camera'),
        ),
    ]
