# Generated by Django 5.1.5 on 2025-03-09 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_camera_remove_detection_location_detection_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='detection.camera'),
        ),
    ]
